### ISSUE TITLE
Plans to maintain hedgehog?

### ISSUE THREAD

**Issue by iferres** [cov-lineages/hedgehog#1]
Hi, I have just read your biorxiv's manuscript and have been trying hedgehog. We have been thinking about using the spike sequences as a cheap proxy to facilitate variant surveillance with nanopore, and your work looks promising.

Are you planing to maintain hedgehog? I saw that it is using a little outdated pango version which may be missing the latest lineages and VOIs, and I suppose the software requires regular updates. 

Also, is there any way to have the information about which linages are assigned to each linage set?

Congrats and thank you for pangolin btw!
Bests!

**Comment by aineniamh** [comment]
Hi @iferres, the plan is to maintain hedgehog for the next while, but it may not be updated as regularly as the pangolin data repository. The lineages in each lineage set are described [here](https://github.com/cov-lineages/hedgehog/blob/main/hedgehog/data/set_names.95.csv). Hope that helps, sorry for the delay replying!
