### ISSUE TITLE
Problem running Hedgehog 1.0.19

### ISSUE THREAD

**Issue by arturomarin** [cov-lineages/hedgehog#2]
Hi, 

I am trying to run hedgehog, but the terminal gives me the following problem:

`/Users/arturo/miniconda3/envs/hedgehog/lib/python3.8/site-packages/pandas/_testing.py:24: FutureWarning: In the future np.bool will be defined as the corresponding NumPy scalar.
  import pandas._libs.testing as _testing
Traceback (most recent call last):
  File "/Users/arturo/miniconda3/envs/hedgehog/bin/hedgehog", line 8, in <module>
    sys.exit(main())
  File "/Users/arturo/miniconda3/envs/hedgehog/lib/python3.8/site-packages/hedgehog/command.py", line 60, in main
    dependency_checks.check_dependencies()
  File "/Users/arturo/miniconda3/envs/hedgehog/lib/python3.8/site-packages/hedgehog/utils/dependency_checks.py", line 41, in check_dependencies
    check_module(module, missing)
  File "/Users/arturo/miniconda3/envs/hedgehog/lib/python3.8/site-packages/hedgehog/utils/dependency_checks.py", line 20, in check_module
    importlib.import_module(module)
  File "/Users/arturo/miniconda3/envs/hedgehog/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/arturo/miniconda3/envs/hedgehog/lib/python3.8/site-packages/pandas/__init__.py", line 179, in <module>
    import pandas.testing
  File "/Users/arturo/miniconda3/envs/hedgehog/lib/python3.8/site-packages/pandas/testing.py", line 5, in <module>
    from pandas._testing import (
  File "/Users/arturo/miniconda3/envs/hedgehog/lib/python3.8/site-packages/pandas/_testing.py", line 24, in <module>
    import pandas._libs.testing as _testing
  File "pandas/_libs/testing.pyx", line 10, in init pandas._libs.testing
  File "/Users/arturo/miniconda3/envs/hedgehog/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
np.bool was a deprecated alias for the builtin bool. To avoid this error in existing code, use bool by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.bool_ here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations`

Maybe it is related to the version of python? my version of python in this environment is 3.8.15 .

Another question that is not clear to me is whether it is necessary to use nucleotide or amino acid sequences for this program, although I have done the tests with both types of sequences and the error is the same.

Any help or suggestion will be welcome.

**Comment by zkkhalil** [comment]
Any resolutions on that end? I am running into the same issue

**Comment by zkkhalil** [comment]
Hi! To add on, I ran into that same issue on a MacOS. When installing it on a Linux system, moving to Python 3.8.2 seemed to work, but all the Omicron samples (those that were being called properly with 1.0.18) came back as A instead of the proper designation like XBB.1.5.

**Comment by aineniamh** [comment]
Thanks! I actually missed this original issue- I've started having a look at this today. My feeling is it'll just be a version conflict issue so will play around with this and see what I can do!

**Comment by aineniamh** [comment]
Okay, i think the versioning issue has been fixed on main now- will be updating the model soon and have some checks in place so can investigate whether the omicron lineages are being accurately assigned then

**Comment by zkkhalil** [comment]
Awesome, thank you! I was able to properly upgrade to 1.0.19 and run it without any errors. Looking forward to the model upgrade :)

**Comment by zkkhalil** [comment]
Hi,

I just wanted to follow up on this to see if the lineage calling has been resolved. I updated to hedgehog v1.1, and it doesn't seem to have been resolved (the omicrons are being called as "A"). Additionally, with the update to v1.1, I am having trouble running hedgehog on a linux system, 

```Error: Missing dependency `pysam`.
Please update your civet environment.```

**Comment by aineniamh** [comment]
Hi @zkkhalil, sorry for the delay, I've been on extended leave- I've just pushed an update for the error message to the main branch. I've tested quite extensively with Omicron sequences on my end and haven't run into any trouble with them being called Omicron. If you have any examples you could share (even anonymous ones) it would be helpful to see what's going on! 

Bear in mind, hedgehog calls lineage sets (denoted by the hash string) and provides the full list of lineages they could be in the output file. I'm trying to think what could be coming up as lineage A and I think you may be looking at the "precision" column potentially? A couple of examples could help track down what's happening! Thanks for your patience, Áine

**Comment by zkkhalil** [comment]
Hi @aineniamh thank you for your response! I am not sure if it is tied to the minimum length argument that we use when running hedgehog. We typically run hedgehog after doing targeted sequencing of the S1 region and so the minimum length used is 2046. I made sure I was running the latest version before my test today using [this](https://drive.google.com/file/d/1uVF_3syMWQ-47-7da27fMwLZHtVD3jpA/view?usp=share_link) FASTA file. The hedgehog, nextclade, and FASTA can all be found [here](https://drive.google.com/drive/folders/1_Y573nT9IEw_tLbfxXMMgEyVeekewazq?usp=share_link). The sequences in this file have also been verified using whole genome sequencing and genotyped using PANGOLIN/Nextclade. The calls from the whole genome match the calls made by Nextclade on just the S1. Thank you for all your help!

**Comment by aineniamh** [comment]
Hi @zkkhalil, sorry for the delay, this took a while to get to the bottom of. I believe the latest model will resolve the problem you're reporting, but I would still caution interpretation as your sequences don't cover the whole spike gene. I've personally never tested on sequences that are that short, so can't say how that will affect the model assignments. If there are some key SNPs missing, there is a good chance the assignment will be inaccurate so just be careful not to overinterpret the result!
