### ISSUE TITLE
Hedgehog reports B.1.617.2_1 for spike sequences with Omicron mutations

### ISSUE THREAD

**Issue by pcparvangada** [cov-lineages/hedgehog#9]
Hi @aineniamh

Thanks for working on this issue! When I feed the programSpike sequences now, I get precision = B.1.1.529

However, when I pass spike sequences from omicron samples, the results are unchanged from before. I still get precision = B.1.617.2_1.

Example sequence:

>example_seq
atgtttgtttttcttgttttattgccactagtctctagtcagtgtgttaatcttataaccagaactcaatcatacactaattctttcacacgtggtgtttattaccctgacaaagttttcagatcctcagttttacattcaactcaggacttgttcttacctttcttttccaatgttacttggttccatgctatacatgtctctgggaccaatggtactaagaggtttgataaccctgccctaccatttaatgatggtgtttattttgcttccactgagaagtctaacataataagaggctggatttttggtactactttagattcgaagacccagtccctacttattgttaataacgctactaatgttgttattaaagtctgtgaatttcaattttgtaatgatccatttttggatgtttaccaaaaaaacaacaaaagttggatggaaagtgagttcagagtttattctagtgcgaataattgcacttttgaatatgtctctcagccttttcttatggaccttgaaggaaaagagggtaatttcaaaaatcttagggaatttgtgtttaagaatattgatggttattttaaaatatattctaagcacacgcctattaatttagagcgtgatctccctcagggtttttcggctttagaaccattggtagatttgccaataggtattaacatcactaggtttcaaactttacttgctttacatagaagttatttgactcctgttgattcttcttcaggttggacagctggtgctgcagcttattatgtgggttatcttcaacctaggacttttctattaaaatataatgaaaatggaaccattacagatgctgtagactgtgcacttgaccctctctcagaaacaaagtgtacgttgaaatccttcactgtagaaaaaggaatctatcaaacttctaactttagagtccaaccaacagaatctattgttagatttcctaatattacaaacttgtgcccttttcatgaagtttttaacgccaccacatttgcatctgtttatgcttggaacaggaagagaatcagcaactgtgttgctgattattctgtcatatataatttcgcaccatttttcgcttttaagtgttatggagtgtctcctactaaattaaatgatctctgctttactaatgtctatgcagattcatttgtaattagaggtaatgaagtcagccaaatcgctccagggcaaactggaaatattgctgattataattataaattaccagatgattttacaggctgcgttatagcttggaattctaacaagcttgattctaagcctagtggtaattataattacctgtatagattgtttaggaagtctaagctcaaaccttttgagagagatatttcaactgaaatctatcaggccggtaacaaaccttgtaatggtgttgcaggtcctaattgttactctcctttacaatcatatggtttccgacccacttatggtgttggtcaccaaccatacagagtagtagtactttcttttgaacttctacatgcaccagcaactgtttgtggacctaaaaagtctactaatttggttaaaaacaaatgtgtcaatttcaacttcaatggtttaacaggcacaggtgttcttactgagtctaacaaaaagtttctgcctttccaacaatttggcagagacattgctgacactactgatgctgtccgtgatccacagacacttgagattcttgacattacaccatgttcttttggtggtgtcagtgttataacaccaggaacaaatacttctaaccaggttgctgttctttatcagggtgttaactgcacagaagtccctgttgctattcatgcagatcaacttactcctacttggcgtgtttattctacaggttctaatgtttttcaaacacgtgcaggctgtttaataggggctgaatatgtcaacaactcatatgagtgtgacatacccattggtgcaggtatatgcgctagttatcagactcagactaagtctcatcggcgggcacgtagtgtagctagtcaatccatcattgcctacactatgtcacttggtgcagaaaattcagttgcttactctaataactctattgccatacccacaaattttactattagtgttaccacagaaattctaccagtgtctatgaccaagacatcagtagattgtacaatgtacatttgtggtgattcaactgaatgcagcaatcttttgttgcaatatggcagtttttgtacacaattaaaacgtgctttaactggaatagctgttgaacaagacaaaaacacccaagaagtttttgcacaagtcaaacaaatttacaaaacaccaccaattaaatattttggtggttttaatttttcacaaatattaccagatccatcaaaaccaagcaagaggtcatttattgaagatctacttttcaacaaagtgacacttgcagatgctggcttcatcaaacaatatggtgattgccttggtgatattgctgctagagacctcatttgtgcacaaaagtttaacggccttactgttttgccacctttgctcacagatgaaatgattgctcaatacacttctgcactgttagcgggtacaatcacttctggttggacctttggtgcaggtgctgcattacaaataccatttgctatgcaaatggcttataggtttaatggtattggagytacacagaatgttctctatgagaaccaaaaattgattgccaaccaatttaatagtgctattgscaaaattcaagactcactttcttccacagcaagtgcacttggaaaacttcaagatgtggtcaaccataatgcacaagctttaaacacgcttgttaaacaacttagctccaaatttggtgcaatttcaagtgttttaaatgatatcctttcacgtcttgacaaagttgaggctgaagtgcaaattgataggttgatcacaggcagacttcaaagtttgcagacatatgtgactcaacaattaattagagctgcagaaatcagagcttctgctaatcttgctgctactaaaatgtcagagtgtgtacttggacaatcaaaaagagttgatttttgtggaaagggctatcatcttatgtccttccctcagtcagcacctcatggtgtagtcttcttgcatgtgacttatgtccctgcacaagaaaagaacttcacaactgctcctgccatttgtcatgatggaaaagcacactttcctcgtgaaggtgtctttgtttcaaatggcacacactggtttgtaacacaaaggaatttttatgaaccacaaatcattactacagacaacacatttgtgtctggtaactgtgatgttgtaataggaattgtcaacaacacagtttatgatcctttgcaacctgaattagattcattcaaggaggagttagataaatattttaagaatcatacatcaccagatgttgatttaggtgacatctctggcattaatgcttcagttgtaaacattcaaaaagaaattgaccgcctcaatgaggttgccaagaatttaaatgaatctctcatcgatctccaagaacttggaaagtatgagcagtatataaaatggccatggtacatttggctaggttttatagctggcttgattgccatagtaatggtgacaattatgctttgctgtatgaccagttgctgtagttgtctcaagggctgttgttcttgtggatcctgctgcaaatttgatgaagacgactctgagccagtgctcaaaggagtcaaattacattacacataa

Looking at the alignment against wuhan reference (NC_045512), the sequence has mutations characteristic of omicron:
S:S373P, S:K417N, S:N440K, S:G446S, S:S477N, S:T478K, S:E484A, S:Q498R, S:N501Y, S:D614G, S:H655Y, S:N679K, S:P681H, S:N764K, S:D796Y, S:Q954H, S:N969K

**Comment by aineniamh** [comment]
Hi @pcparvangada, can I check what version of hedgehog you're running? I've just ran your example sequence through and got the following:

```
taxon,set_name,set_hash,precision,set_description,lineage_count,spike_constellation,conflict,ambiguity_score,hedgehog_version,pango_version,status,note
example_seq,072d50,072d508a35616a073943a44211a34045,BA.2,BA.2_1,77,S:T19I|del:21633:9|S:V83A|S:G142D|del:21991:3|S:H146Q|S:Q183E|S:V213E|S:G252V|S:G339H|S:R346T|S:L368I|S:S371F|S:S373P|S:S375F|S:T376A|S:D405N|S:R408S|S:K417N|S:N440K|S:V445P|S:G446S|S:N460K|S:S477N|S:T478K|S:E484A|S:F486P|S:F490S|S:Q498R|S:N501Y|S:Y505H|S:D614G|S:H655Y|S:N679K|S:P681H|S:N764K|S:D796Y|S:Q954H|S:N969K|synSNP:C25000T,0.0,0.9997296566639632,1.4.1,1.21,passed_qc,
```
suggesting it is a BA.2-type sequence. 

Also, just for interpretation- the list of mutations reported is the 60% CSH (consensus spike haplotype) for that lineage set, meaning for each lineage in the lineage set, 60% of designated sequences carry these SNPs. It doesn't necessarily mean your query sequence will contain all of the reported SNPs.

**Comment by pcparvangada** [comment]
hi @aineniamh 

I updated the version and get accurate results now. Thanks for all your help!

**Comment by aineniamh** [comment]
Fantastic, glad it's working for you!
